In [4]:
import requests

In [7]:
URL = "https://stephen-king-api.onrender.com/api/books"


res  = requests.get(URL)

In [8]:
res

In [45]:
json_data = res.json() # data

In [14]:
import pandas as pd

In [26]:
df =pd.json_normalize(json_data["data"])
df = df[['id','Title','Year','ISBN']]

In [49]:
df

    id          Title  Year               ISBN
0    1         Carrie  1974  978-0-385-08695-0
1    2    Salem's Lot  1975  978-0-385-00751-1
2    3    The Shining  1977  978-0-385-12167-5
3    4           Rage  1977  978-0-451-07645-8
4    5      The Stand  1978  978-0-385-12168-2
..  ..            ...   ...                ...
58  59   The Outsider  2018  978-1-50118-098-9
59  60      Elevation  2018  978-1-98210-231-9
60  61  The Institute  2019  978-1-98211-056-7
61  62          Later  2021  978-1-78909-649-1
62  63  Billy Summers  2021  978-1-982-17361-6

[63 rows x 4 columns]

In [50]:
URL1 = "https://stephen-king-api.onrender.com/api/books"

In [51]:
res = requests.get(URL)

In [52]:
res

In [57]:
json_data = res.json()

In [64]:
df1 = pd.json_normalize(json_data["data"])

In [65]:
df1 = df1[['id','Year']]

In [66]:
df1

    id  Year
0    1  1974
1    2  1975
2    3  1977
3    4  1977
4    5  1978
..  ..   ...
58  59  2018
59  60  2018
60  61  2019
61  62  2021
62  63  2021

[63 rows x 2 columns]